#pragma once

#include <config.h>

#define PAGE_ALIGN_UP(a) ALIGN_UP(a, PAGE_SIZE)
#define PAGE_ALIGN_DOWN(a) ALIGN_DOWN(a, PAGE_SIZE)
#define PAGE_ALIGNED(a) ALIGNED(a, PAGE_SIZE)

#define SLAB_ALIGN_UP(a) ALIGN_UP(a, SLAB_BLOB_SIZE)
#define SLAB_ALIGN_DOWN(a) ALIGN_DOWN(a, SLAB_BLOB_SIZE)
#define SLAB_ALIGNED(a) ALIGNED(a, SLAB_BLOB_SIZE)

#define BUDDY_ALIGN_UP(a) ALIGN_UP(a, BUDDY_BLOB_SIZE)
#define BUDDY_ALIGN_DOWN(a) ALIGN_DOWN(a, BUDDY_BLOB_SIZE)
#define BUDDY_ALIGNED(a) ALIGNED(a, BUDDY_BLOB_SIZE)
